/* Downloads the webfonts and rewrites the stylesheet to serve them from our own
 * origin. Loading fonts from Google's CDN sends every visitor's IP address to a
 * third party on page load — a German court (LG München I, 3 O 17493/20) held
 * that doing it without consent breached the GDPR. Self-hosting removes the
 * request entirely, which is also what lets the privacy page say, truthfully,
 * that the site makes no third-party requests at all.
 *
 *   npm run fonts
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "site", "fonts");
mkdirSync(out, { recursive: true });

const URL_CSS = "https://fonts.googleapis.com/css2?family=Poppins:wght@500;600;700&family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600&display=swap";
/* A modern UA gets woff2 back; an old one gets ttf, which is four times larger. */
const UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

const css = await (await fetch(URL_CSS, { headers: { "User-Agent": UA } })).text();

/* Keep only the latin and latin-ext subsets: the page has no other scripts. */
const blocks = css.split("/*").map((b) => "/*" + b).filter((b) => /^\/\*\s*(latin|latin-ext)\s*\*\//.test(b.trim()));

let n = 0;
let localCss = `/* Self-hosted webfonts. Generated by fetch-fonts.mjs — do not edit.
   Poppins, Plus Jakarta Sans and JetBrains Mono are licensed under the
   SIL Open Font License 1.1; see NOTICE.md. */\n`;

for (const block of blocks) {
  const url = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
  const subset = block.match(/^\/\*\s*([a-z-]+)\s*\*\//)?.[1];
  if (!url || !family) continue;
  const file = `${family.toLowerCase().replace(/\s+/g, "-")}-${weight}-${subset}.woff2`;
  const bytes = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
  writeFileSync(join(out, file), bytes);
  n++;
  localCss += block.replace(/url\(https:[^)]+\.woff2\)/, `url(fonts/${file})`).trim() + "\n";
}

writeFileSync(join(here, "site", "fonts.css"), localCss);
console.log(`${n} font files -> transfer-odds/site/fonts/`);
