/* Generated by tools/split-paid.mjs — do not edit by hand.
 *
 * The income band labels, and nothing else. The figures they index into are a
 * paid feature and are not in this bundle: see worker/data/costs.txt, which
 * only the entitlement API returns. This file exists so the free app can still
 * render the income control, explain what it is for, and say what it would
 * buy you.
 */

export const INCOME_BANDS = [
  ["u30", "Under $30,000"],
  ["30to48", "$30,000 to $48,000"],
  ["48to75", "$48,000 to $75,000"],
  ["75to110", "$75,000 to $110,000"],
  ["over110", "Over $110,000"],
];
