/* Builds assist.js — the identifiers needed to deep-link into ASSIST.
 *
 * ASSIST is the official articulation repository for California's public
 * colleges, run by the Regents, and its content is copyrighted. This file
 * therefore carries no articulation data at all: only the institution
 * identifiers and academic year needed to construct a link INTO assist.org,
 * so a reader lands on the agreement itself rather than on our summary of it.
 *
 * The identifiers come from assist.org's own /api/institutions, read once
 * through the site in a browser (the endpoint is antiforgery-token bound).
 * Run: node tools/build-assist.mjs  — writes ../assist.js
 */
import { readFileSync, writeFileSync } from "fs";
import { SCHOOLS } from "../model.js";

const d = JSON.parse(readFileSync(new URL("./assist-institutions.json", import.meta.url)));
const norm = (x) => x.toLowerCase().replace(/[^a-z0-9]/g, "");

/* ASSIST spells five campuses differently from the federal directory. */
const ALSO = {
  "California Polytechnic State University, San Luis Obispo": "California Polytechnic University, San Luis Obispo",
  "California State Polytechnic University, Pomona": "California Polytechnic University, Pomona",
  "California State Polytechnic University, Humboldt": "California Polytechnic University, Humboldt",
  "Mount Saint Mary's University": "Mount Saint Mary's University Los Angeles",
  "Vanguard University": "Vanguard University of Southern California",
};

const idx = new Map();
for (const i of d.inst) for (const n of i.names) if (!idx.has(norm(n.name))) idx.set(norm(n.name), i);

const recv = [];
for (const s of SCHOOLS.filter((s) => s.state === "CA")) {
  const i = idx.get(norm(ALSO[s.name] || s.name));
  if (i && !i.isCommunityCollege) recv.push([s.name, i.id]);
}

/* Every community college, so a reader's own campus can be matched from the
   free-text field they typed it into. */
const ccs = d.inst.filter((i) => i.isCommunityCollege)
  .map((i) => [i.names[i.names.length - 1].name, i.id])
  .sort((a, b) => a[0].localeCompare(b[0]));

const year = d.years.reduce((a, y) => (y.fallYear === 2026 ? y : a), null);
if (!year) throw new Error("no 2026-2027 academic year in the ASSIST feed");

writeFileSync(new URL("../assist.js", import.meta.url), `/* Generated by tools/build-assist.mjs — do not edit by hand.
 *
 * Identifiers for deep-linking into assist.org, the official articulation
 * repository for California's public colleges. No articulation content is
 * copied here; ASSIST's own pages are linked instead, because they are
 * authoritative, they are copyrighted by the Regents, and they change under us.
 *
 * ${recv.length} of the California schools in this app take part in ASSIST.
 * The rest — Stanford, USC, Caltech, the Claremont colleges — do not, and are
 * absent rather than linked to a page that would not have them.
 */

export const ASSIST_YEAR = ${year.id};            // 2026–2027, the live catalogue
export const ASSIST_YEAR_LABEL = "2026–2027";

/* school name -> ASSIST receiving institution id */
export const ASSIST_RECEIVING = new Map(${JSON.stringify(recv.sort((a, b) => a[0].localeCompare(b[0])))});

/* community college name -> ASSIST sending institution id */
export const ASSIST_SENDING = new Map(${JSON.stringify(ccs)});
`);
console.log(`assist.js — ${recv.length} receiving, ${ccs.length} community colleges, year ${year.id}`);
