/* Build costs.js from the College Scorecard institution file.
 *
 *   node tools/build-costs.mjs Most-Recent-Cohorts-Institution.csv 06102026
 *
 * Two things the odds model cannot tell you: what a year there actually costs
 * you, and whether people finish.
 *
 * NET PRICE is the number that matters and the one nobody quotes. It is the
 * published price minus the grants a student actually received — what the
 * family paid. It varies enormously by income: Harvard's sticker is $61,676
 * and its net price is $2,091 for a household earning $48–75k and $53,337
 * for one over $110k. Quoting one average across all incomes would be worse
 * than quoting nothing, so the brackets are carried separately and the app
 * asks which one applies.
 *
 * GRADUATION RATE carries a caveat this app in particular has to state: the
 * federal figure counts only first-time, full-time students, which by
 * definition EXCLUDES transfer students. It describes the campus, not people
 * arriving the way this app's readers are arriving. It is still worth showing
 * — a school where 3 in 10 freshmen finish is telling you something — but it
 * is not a transfer completion rate, and nothing here should imply it is.
 *
 * Public domain (17 U.S.C. § 105). https://collegescorecard.ed.gov/data/
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..");
const csvPath = process.argv[2];
const release = process.argv[3] || (csvPath?.match(/_(\d{8})/) || [, "unknown"])[1];
if (!csvPath) {
  console.error("usage: node tools/build-costs.mjs <institution.csv> [release]");
  process.exit(1);
}

const linkSrc = readFileSync(join(repo, "links.js"), "utf8");
const UNITS = new Set();
for (const line of linkSrc.match(/export const LINK_ROWS = `\n([\s\S]*?)\n`/)[1].trim().split("\n")) {
  const id = line.split("|")[1];
  if (id && id.trim()) UNITS.add(id.trim());
}

/* Same quoted-CSV reader the programs build uses: institution names carry commas. */
function* rows(text) {
  let field = "", row = [], quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"') { if (text[i + 1] === '"') { field += '"'; i++; } else quoted = false; }
      else field += c;
    } else if (c === '"') quoted = true;
    else if (c === ",") { row.push(field); field = ""; }
    else if (c === "\n") { row.push(field); yield row; row = []; field = ""; }
    else if (c !== "\r") field += c;
  }
  if (field || row.length) { row.push(field); yield row; }
}

const it = rows(readFileSync(csvPath, "utf8"));
const header = it.next().value.map((h) => h.replace(/^﻿/, ""));
const col = Object.fromEntries(header.map((h, i) => [h, i]));
const NEED = ["UNITID", "CONTROL", "NPT4_PUB", "NPT4_PRIV", "TUITIONFEE_IN", "TUITIONFEE_OUT", "C150_4", "RET_FT4"];
for (const k of NEED) if (col[k] === undefined) throw new Error(`column ${k} missing — the Scorecard layout changed`);

/* Net price can legitimately be negative: at a handful of very well-endowed
   schools the grant aid for the lowest income bands exceeds the whole cost of
   attendance, and the student receives the difference. Caltech reports
   -$2,133 under $30k. Rejecting the minus sign silently dropped exactly the
   figures most worth showing, so the sign is kept and the app explains it. */
const num = (v) => (/^-?\d+(\.\d+)?$/.test(v) ? Number(v) : null);
const hundreds = (v) => (v === null ? "" : Math.round(v / 100));
const pct = (v) => (v === null ? "" : Math.round(v * 100));

const out = [];
let withNet = 0, withGrad = 0, brackets = 0;

for (const r of it) {
  if (r.length < header.length) continue;
  const unitid = r[col.UNITID];
  if (!UNITS.has(unitid)) continue;

  /* A school reports its net price under the public or the private columns,
     never both. Which one is a fact about the school, not about the reader. */
  const pub = num(r[col.CONTROL]) === 1;
  const suffix = pub ? "_PUB" : "_PRIV";
  const net = num(r[col[`NPT4${suffix}`]]);
  const byIncome = [1, 2, 3, 4, 5].map((i) => num(r[col[`NPT4${i}${suffix}`]]));

  const row = [
    unitid,
    hundreds(net),
    ...byIncome.map(hundreds),
    hundreds(num(r[col.TUITIONFEE_IN])),
    hundreds(num(r[col.TUITIONFEE_OUT])),
    pct(num(r[col.C150_4])),
    pct(num(r[col.RET_FT4])),
  ].join("|").replace(/\|+$/, "");

  if (net !== null) withNet++;
  if (num(r[col.C150_4]) !== null) withGrad++;
  if (byIncome.every((v) => v !== null)) brackets++;
  out.push(row);
}

out.sort((a, b) => a.localeCompare(b));

const file = `/* What a year costs, and whether people finish.
 *
 * Generated by tools/build-costs.mjs from the U.S. Department of Education
 * College Scorecard institution file, release ${release}. Public domain.
 * Do not edit by hand — regenerate instead.
 *
 * COST_ROWS  unitid | net price | net by income band 1-5 | tuition in-state |
 *            tuition out-of-state | graduation rate | retention rate
 *
 * Money is in hundreds of dollars, rates are whole percents, and any field may
 * be empty, which means the Department did not publish it. Trailing empties
 * are dropped.
 *
 * NET PRICE is published price minus the grant aid students actually received.
 * The five bands are household income: under $30k, $30-48k, $48-75k, $75-110k,
 * and over $110k. They differ enormously — reporting the average alone would
 * mislead most readers — so the app asks which band applies rather than
 * picking one.
 *
 * GRADUATION RATE counts first-time, full-time students only, and therefore
 * excludes transfer students by construction. It describes the campus, not
 * people arriving the way this app's readers are arriving, and the app says so
 * wherever it appears.
 */

export const INCOME_BANDS = [
  ["u30", "Under $30,000"],
  ["30to48", "$30,000 to $48,000"],
  ["48to75", "$48,000 to $75,000"],
  ["75to110", "$75,000 to $110,000"],
  ["over110", "Over $110,000"],
];

export const COST_ROWS = \`
${out.join("\n")}
\`.trim();
`;

writeFileSync(join(repo, "costs.js"), file);
console.log(`${out.length} schools`);
console.log(`  ${withNet} carry an average net price (${Math.round((withNet / out.length) * 100)}%)`);
console.log(`  ${brackets} carry all five income bands (${Math.round((brackets / out.length) * 100)}%)`);
console.log(`  ${withGrad} carry a graduation rate (${Math.round((withGrad / out.length) * 100)}%)`);
console.log(`costs.js — ${(file.length / 1024).toFixed(0)} KB`);
