/* Split the generated tables into what a free browser may hold and what only
 * the entitlement API may return.
 *
 * The paywall is server-side or it does not exist. Everything this app ships
 * to the browser is readable in view-source, so "paid" data cannot live in the
 * bundle behind an if-statement — it has to not be there at all. This script
 * is what makes that true, and it runs before the site is built.
 *
 * Free keeps what makes the app useful enough to be worth paying for:
 * admission estimates, the fits slate, and how big a program is. Paid is the
 * money and the outcomes — net price by income band, graduation and retention,
 * graduate earnings and debt.
 *
 *   costs.js       -> income-bands.js (free)  + worker/data/costs.txt (paid)
 *   programs.js    -> money columns stripped  + worker/data/earnings.txt (paid)
 *
 * Run: node tools/split-paid.mjs
 */
import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (f) => readFileSync(join(root, f), "utf8");
const block = (src, name) => {
  const m = src.match(new RegExp("export const " + name + " = `\\n([\\s\\S]*?)`\\s*(?:\\.trim\\(\\))?;"));
  if (!m) throw new Error(`no ${name} block`);
  return m[1].replace(/\n$/, "");
};

/* ---- costs: the whole table is paid, the band labels are not ---- */
const costs = read("costs.js");
const costRows = block(costs, "COST_ROWS");
const bands = costs.match(/export const INCOME_BANDS = \[[\s\S]*?\];/)[0];

writeFileSync(join(root, "income-bands.js"), `/* Generated by tools/split-paid.mjs — do not edit by hand.
 *
 * The income band labels, and nothing else. The figures they index into are a
 * paid feature and are not in this bundle: see worker/data/costs.txt, which
 * only the entitlement API returns. This file exists so the free app can still
 * render the income control, explain what it is for, and say what it would
 * buy you.
 */

${bands}
`);
writeFileSync(join(root, "worker/data/costs.txt"), costRows + "\n");

/* ---- programs: keep the award counts, take out the money ---- */
const programs = read("programs.js");
const progRows = block(programs, "PROGRAM_ROWS");

const freeLines = [], paidLines = [];
for (const line of progRows.split("\n")) {
  if (!line) continue;
  const [head, fields] = line.split(":");
  if (!fields) { freeLines.push(line); continue; }
  const free = [], paid = [];
  for (const f of fields.split(";")) {
    const [cip, awards, e1, e2, debt] = f.split(",");
    free.push(`${cip},${awards}`);
    /* Only carry a field that actually has a figure — most of the table is
       suppressed for small cohorts, and empty triples are pure weight. */
    if (e1 || e2 || debt) paid.push(`${cip},${e1 || ""},${e2 || ""},${debt || ""}`);
  }
  freeLines.push(`${head}:${free.join(";")}`);
  if (paid.length) paidLines.push(`${head.split(",")[0]}:${paid.join(";")}`);
}

writeFileSync(join(root, "programs.js"),
  programs.replace(/export const PROGRAM_ROWS = `\n[\s\S]*?`(\s*(?:\.trim\(\))?);/,
    (_, t) => "export const PROGRAM_ROWS = `\n" + freeLines.join("\n") + "\n`" + t + ";"));
writeFileSync(join(root, "worker/data/earnings.txt"), paidLines.join("\n") + "\n");

const kb = (s) => (Buffer.byteLength(s) / 1024).toFixed(1) + " KB";
console.log(`free  programs.js  PROGRAM_ROWS ${kb(freeLines.join("\n"))}`);
console.log(`paid  costs.txt    ${kb(costRows)}`);
console.log(`paid  earnings.txt ${kb(paidLines.join("\n"))}  (${paidLines.length} schools)`);
